version: "3.8"

services:
  client-prod:
    container_name: prod-client-789bet
    image: ${IMAGE_APP_TAG}
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ENV_ENVIROMENT=prod
      - NEXT_PUBLIC_API_URL=
      - NEXT_PUBLIC_SITE_URL=
      - NEXT_TELEMETRY_DEBUG=0
    ports:
      - "3022:3000"
    restart: always
    dns:
      - 8.8.8.8
      - 8.8.4.4

